
# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Сборка контейнера
      run: docker build . -t ${{ secrets.DOCKER_USER }}/newsapp:latest -f WebApplication1/Dockerfile
    - name: Авторизация в Docker
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_SECRET }}
    - name: Отправка контейнера
      run: docker push ${{ secrets.DOCKER_USER }}/newsapp
    - name: Запуск контейнера
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_TOKEN }}
        script_stop: true
        script: |
          docker pull ${{ secrets.DOCKER_USER }}/newsapp:latest
          docker stop newsapp || true
          docker rm newsapp || true
          docker run -d -p 80:80 --name newsapp ${{ secrets.DOCKER_USER }}/newsapp:latest
